# From https://medium.com/@pierreprinetti/the-go-dockerfile-d5d43af9ee3c
FROM golang:1.13 AS builder

# Download and install the latest release of dep
ADD https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

# Copy the code from the host and compile it
WORKDIR /go/src/github.com/fberrez/scrooge/
COPY Gopkg.toml Gopkg.lock ./
ADD cmd/balance ./cmd/balance
ADD balance ./balance/
ADD scrooge ./scrooge/
COPY Makefile ./Makefile
RUN dep ensure --vendor-only
RUN CGO_ENABLED=0 make balance 

FROM scratch
COPY --from=builder /go/src/github.com/fberrez/scrooge/output/balance ./
ENTRYPOINT ["./balance"]
